In [ ]:
#Task 1
import numpy as np
X = np.arange(2, 33, 2).reshape(4, 4)

print(X)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [ ]:
#Task 2
import numpy as np

X = np.arange(1, 26).reshape(5, 5)
Y = X[X % 2 != 0]

print("Original array X:")
print(X)

print("\nArray Y with odd numbers:")
print(Y)


Original array X:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array Y with odd numbers:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [ ]:
#Task 3
import numpy as np

X = np.arange(1, 5).reshape(4, 1) * np.ones((1, 4))

print(X)


[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]
